### PR TITLE
Support the path_namespace key in match rules

### PR DESCRIPTION
**Pull request by hpdeifel**
path_namespace was introduced in version 0.16 of the dbus specification
in 2011. It allows to match messages from all objects in the hierarchy
below the given path.

_I sent this patch to the original author about two years ago, but never got a response_

### CODE REVIEW

**Comment by rblaze** [comment]
How come I never got any notifications about this repo? Sorry about delay, I'll take a look ASAP.

**Comment by rblaze** [comment]
Looks like tests are broken in the master branch too. Merging this diff. I'll make new release after taking a look at the tests.

**Comment by hpdeifel** [comment]
Thank you very much!

**Comment by rblaze** [comment]
Hi! I'm looking into changing library license from GPL to Apache. Are you okay with releasing your changes under Apache license?

**Comment by hpdeifel** [comment]
Yes

**Pull request merged**
